# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: mlops-pipeline-azure
dependencies:
- python=3.8
- pip:
  - numpy==1.16.0
  - azure-cli-core==2.0.*
  - azureml-core==1.23.0
  - dynaconf==3.1.2
  - notebook
  - ipykernel
channels:
- conda-forge
